# Generated by Django 5.2.5 on 2025-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("room", "Room"),
                    ("storage", "Storage"),
                    ("shelf", "Shelf"),
                    ("container", "Container"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
