# Generated by Django 5.2.5 on 2025-08-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_location_barcode_location_is_container_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="cleaned_duration",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Duration in days before this location needs cleaning again",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="cleaned_time",
            field=models.DateTimeField(
                blank=True, help_text="When this location was last cleaned", null=True
            ),
        ),
    ]
