# Generated by Django 5.2.5 on 2025-08-31 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_location_cleaned_duration_location_cleaned_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="cleaned_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When this location was last cleaned",
            ),
            preserve_default=False,
        ),
    ]
