# Generated by Django 5.2.5 on 2025-09-02 16:49

import locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_location_cleaned_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationimage",
            name="image",
            field=models.ImageField(
                upload_to=locations.models.location_image_upload_path
            ),
        ),
    ]
