# Generated by Django 5.2.5 on 2025-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_locationimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationimage",
            name="image",
            field=models.ImageField(upload_to="location_images/"),
        ),
    ]
