# Generated by Django 5.2.5 on 2025-09-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_alter_locationimage_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["path"], name="locations_l_path_335167_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["location_type"], name="locations_l_locatio_aa6df5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_container"], name="locations_l_is_cont_c031b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["created_at"], name="locations_l_created_c17f75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["cleaned_time"], name="locations_l_cleaned_fb1edb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["barcode"], name="locations_l_barcode_91f7e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["name"], name="locations_l_name_0dcc82_idx"),
        ),
    ]
